import { Component, OnInit } from '@angular/core';

import { Title } from '@angular/platform-browser';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-unboxings-list',
  templateUrl: './unboxings-list.component.html',
  styleUrls: ['./unboxings-list.component.scss']
})
export class UnboxingsListComponent implements OnInit {
  public unboxingsItems = [
    {
      id: 1,
      country: 'USA',
      itemName: 'Rolex Datejust 16030',
      boxName: 'Rolex Premium',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Rolex_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 2,
      country: 'USA',
      itemName: 'Louis Vuitton Run Away',
      boxName: 'Louis Vuitton Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Supreme_3.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 3,
      country: 'Mexico',
      itemName: 'MacBook Pro 13',
      boxName: 'Apple Premium',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_apple_2.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 4,
      country: 'Spain',
      itemName: 'Yeezy 350 V2 Citrin',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 5,
      country: 'USA',
      itemName: 'Jordan 1 Travis Scott',
      boxName: 'Travis Deluxe',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 6,
      country: 'France',
      itemName: 'Apple iMac',
      boxName: 'Apple Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_3.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 7,
      country: 'Australia',
      itemName: 'Nintendo Switch',
      boxName: 'Nintendo Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_nintendo_2.png',
      countryImage: 'assets/images/country-flags/AU.svg',
    },
    {
      id: 8,
      country: 'USA',
      itemName: 'Jordan 9 Retro Racer',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 9,
      country: 'USA',
      itemName: 'BAPE College Tee',
      boxName: 'Bape Budget',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_bape_4.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 10,
      country: 'Spain',
      itemName: 'Yeezy 350 V2 Semi Frozen',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 11,
      country: 'Germany',
      itemName: 'iPhone 11',
      boxName: 'iPhone Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_1-1.png',
      countryImage: 'assets/images/country-flags/DE.svg',
    },
    {
      id: 12,
      country: 'USA',
      itemName: 'Yeezy Slide Bone',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 13,
      country: 'USA',
      itemName: 'Yeezy 350 V2 Black',
      boxName: 'Yeezy Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Boost_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 14,
      country: 'USA',
      itemName: 'Statue of Liberty Jacket',
      boxName: 'Supreme X The North Face',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_northface_2.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 15,
      country: 'Canada',
      itemName: 'Jordan 5 Retro Fire',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/CA.svg',
    },
    {
      id: 16,
      country: 'Portugal',
      itemName: 'Travis Scott T-Shirt',
      boxName: 'Travis Premium',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_1.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 17,
      country: 'USA',
      itemName: 'Off-White Flannel',
      boxName: 'Off-White Premium',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_offwhite_2.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 18,
      country: 'Spain',
      itemName: 'Yeezy 350 V2 Core Black',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 19,
      country: 'Spain',
      itemName: 'Yeezy Calabasas Pants',
      boxName: 'Yeezy Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Boost_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 20,
      country: 'UK',
      itemName: 'Yeezy 350 V2 Zebra',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'jpeg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/GB.svg',
    },
    {
      id: 21,
      country: 'USA',
      itemName: 'LD Waffle Sacai',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 22,
      country: 'Sweden',
      itemName: 'iPhone 11',
      boxName: 'Apple Premium',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_apple_2.png',
      countryImage: 'assets/images/country-flags/SE.svg',
    },
    {
      id: 23,
      country: 'Spain',
      itemName: 'Dunk Low Off-White Pine',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 24,
      country: 'Mexico',
      itemName: 'Yeezy 350 V2 Static Black',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 25,
      country: 'Portugal',
      itemName: 'Supreme Shoulder Bag',
      boxName: 'Supreme Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_1.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 26,
      country: 'Brazil',
      itemName: 'iPhone 11',
      boxName: 'iPhone Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_1-1.png',
      countryImage: 'assets/images/country-flags/BR.svg',
    },
    {
      id: 27,
      country: 'USA',
      itemName: 'Balenciaga Triple S',
      boxName: 'Balenciaga Deluxe',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Balenciaga_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 28,
      country: 'Portugal',
      itemName: 'Cactus Jack T-Shirt',
      boxName: 'Travis Deluxe',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_1.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 29,
      country: 'Mexico',
      itemName: 'Supreme Axe',
      boxName: 'Supreme Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_2.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 30,
      country: 'USA',
      itemName: 'Apple AirPods 2',
      boxName: 'iPhone Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_1-1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 31,
      country: 'Mexico',
      itemName: 'Nintendo Switch Lite',
      boxName: 'Nintendo Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_nintendo_2.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 32,
      country: 'Canada',
      itemName: 'Yeezy 350 V2 Zebra',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/CA.svg',
    },
    {
      id: 33,
      country: 'Portugal',
      itemName: 'Travis Scott T-Shirt',
      boxName: 'Travis Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_3.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 34,
      country: 'USA',
      itemName: 'Razer Keyboard',
      boxName: 'Razer Premium',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Razer_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 35,
      country: 'Spain',
      itemName: 'LD Waffle Sacai Green',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 37,
      country: 'USA',
      itemName: 'Jordan 6 Retro Travis Scott',
      boxName: 'Travis Deluxe',
      type: 'video',
      expansion: 'MOV',
      videoPreview: 'assets/images/unboxings/37-video-poster.png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 38,
      country: 'Italy',
      itemName: 'Yeezy 350 V2 Zebra',
      boxName: 'Yeezy Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/Adidas_1.png',
      countryImage: 'assets/images/country-flags/IT.svg',
    },
    {
      id: 39,
      country: 'Sweden',
      itemName: 'Supreme Camo Bag',
      boxName: 'Supreme Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_2.png',
      countryImage: 'assets/images/country-flags/SE.svg',
    },
    {
      id: 40,
      country: 'Mexico',
      itemName: 'Keychain Supreme',
      boxName: 'Supreme Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_1.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: '40a',
      country: 'Switzerland',
      itemName: 'Yeezy Boost Antlia',
      boxName: 'Yeezy Lucky',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Boost_1.png',
      countryImage: 'assets/images/country-flags/CH.svg',
    },
    {
      id: 41,
      country: 'Portugal',
      itemName: 'Off-White Pants',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 42,
      country: 'Germany',
      itemName: 'Iphone 11',
      boxName: 'Apple Premium',
      type: 'video',
      expansion: 'mp4',
      videoPreview: 'assets/images/unboxings/42-video-poster.png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_apple_2.png',
      countryImage: 'assets/images/country-flags/DE.svg',
    },
    {
      id: 43,
      country: 'USA',
      itemName: 'Louis Vuitton Wallet',
      boxName: 'Supreme X Louis Vuitton',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_LV_Supreme.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 44,
      country: 'France',
      itemName: 'Gaming PC GTX 1080',
      boxName: 'PC premium',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_build_a_pc_3.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 45,
      country: 'Spain',
      itemName: 'Bape Tights',
      boxName: 'Bape Budget',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_bape_4.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 46,
      country: 'Portugal',
      itemName: 'Travis Scott Keychain',
      boxName: 'Travis Deluxe',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_1.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 47,
      country: 'Belgium',
      itemName: 'Nintendo Switch',
      boxName: 'Nintendo Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_nintendo_2.png',
      countryImage: 'assets/images/country-flags/BE.svg',
    },
    {
      id: 48,
      country: 'Ukraine',
      itemName: 'HyperX headset',
      boxName: 'PC budget',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_build_a_pc_3.png',
      countryImage: 'assets/images/country-flags/UA.svg',
    },
    {
      id: 49,
      country: 'Netherlands',
      itemName: 'Apple Watch',
      boxName: 'Apple Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_3.png',
      countryImage: 'assets/images/country-flags/NL.svg',
    },
    {
      id: 50,
      country: 'Brazil',
      itemName: 'Yeezy Yechiel',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/BR.svg',
    },
    {
      id: 51,
      country: 'France',
      itemName: 'Yeezy Hospital Blue',
      boxName: 'Yeezy Lucky',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Boost_1.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 52,
      country: 'France',
      itemName: 'Off-White Kiger 5',
      boxName: 'Off-White Lucky',
      type: 'image',
      expansion: 'JPG',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Offwhite_1.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 53,
      country: 'USA',
      itemName: 'Off-White University',
      boxName: 'Off-White Premium',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_offwhite_2.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 54,
      country: 'Portugal',
      itemName: 'Balenciaga Multi Card',
      boxName: 'Balenciaga Premium',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-dev.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 55,
      country: 'Austria',
      itemName: 'New Imac Pro',
      boxName: 'Apple Premium',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_apple_2.png',
      countryImage: 'assets/images/country-flags/AT.svg',
    },
    {
      id: 56,
      country: 'Japan',
      itemName: 'Yeezy Boost Butter',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'PNG',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/JP.svg',
    },
    {
      id: 57,
      country: 'Spain',
      itemName: 'Nike Sneaker',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 58,
      country: 'Taiwan',
      itemName: 'Magic Mouse 2',
      boxName: 'Apple Box',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_3.png',
      countryImage: 'assets/images/country-flags/TW.svg',
    },
    {
      id: 59,
      country: 'Portugal',
      itemName: 'Travis Scott Sweatpants',
      boxName: 'Travis Lucky',
      type: 'image',
      expansion: 'jfif',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_3.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 60,
      country: 'USA',
      itemName: 'Yeezy Zebra',
      boxName: 'Yeezy Lucky',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Boost_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 61,
      country: 'Spain',
      itemName: 'Supreme Backpack',
      boxName: 'Supreme Budget',
      type: 'image',
      expansion: 'jfif',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 62,
      country: 'Mexico',
      itemName: 'Yeezy Zebra',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'PNG',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 63,
      country: 'France',
      itemName: 'Yeezy 500 Vision',
      boxName: 'Yeezy Peasy',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_002_Yeeze.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 64,
      country: 'Mexico',
      itemName: 'Jordan 1 Royal',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 65,
      country: 'Spain',
      itemName: 'Supreme Lighter',
      boxName: 'Supreme Summer',
      type: 'image',
      expansion: 'jfif',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_1-6.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 66,
      country: 'Spain',
      itemName: 'Off-White foam',
      boxName: 'Nike Budget',
      type: 'image',
      expansion: 'jfif',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 67,
      country: 'Taiwan',
      itemName: 'AirPods 2',
      boxName: 'Apple Premium',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_apple_2.png',
      countryImage: 'assets/images/country-flags/TW.svg',
    },
    {
      id: 68,
      country: 'USA',
      itemName: 'Yeezy Boost Antlia',
      boxName: 'Yeezy Lucky',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Boost_1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 69,
      country: 'Spain',
      itemName: 'Off-White Vaper',
      boxName: 'Off-White Premium',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_offwhite_2.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 70,
      country: 'France',
      itemName: 'Supreme T-Shirt',
      boxName: 'Supreme Lucky',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_2.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 71,
      country: 'Mexico',
      itemName: 'Air Force Cactus',
      boxName: 'Travis Deluxe',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_travis_scott_1.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 72,
      country: 'Portugal',
      itemName: 'Fear Of God T-Shirt',
      boxName: 'Fear Of God',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Kaws.png',
      countryImage: 'assets/images/country-flags/PT.svg',
    },
    {
      id: 73,
      country: 'Sweden',
      itemName: 'Supreme T-Shirt',
      boxName: 'Supreme Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_1.png',
      countryImage: 'assets/images/country-flags/SE.svg',
    },
    {
      id: 74,
      country: 'USA',
      itemName: 'Airpods',
      boxName: 'Iphone Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_1-1.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 75,
      country: 'Mexico',
      itemName: 'Jordan Cool Grey',
      boxName: 'Hype Mix',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Logos.png',
      countryImage: 'assets/images/country-flags/MX.svg',
    },
    {
      id: 76,
      country: 'Canada',
      itemName: 'Airpods',
      boxName: 'Apple Box',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_3.png',
      countryImage: 'assets/images/country-flags/CA.svg',
    },
    {
      id: 77,
      country: 'USA',
      itemName: 'Fear Of God T-Shirt',
      boxName: 'Fear Of God',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Kaws.png',
      countryImage: 'assets/images/country-flags/US.svg',
    },
    {
      id: 78,
      country: 'France',
      itemName: 'Supreme Keychain',
      boxName: 'Supreme Lucky',
      type: 'image',
      expansion: 'png',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_2.png',
      countryImage: 'assets/images/country-flags/FR.svg',
    },
    {
      id: 79,
      country: 'Spain',
      itemName: 'Supreme T-Shirt',
      boxName: 'Supreme Budget',
      type: 'image',
      expansion: 'jpg',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Box_supreme_1.png',
      countryImage: 'assets/images/country-flags/ES.svg',
    },
    {
      id: 80,
      country: 'Switzerland',
      itemName: 'AirPods 2',
      boxName: 'iPhone Box',
      type: 'image',
      expansion: 'PNG',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Apple_1-1.png',
      countryImage: 'assets/images/country-flags/CH.svg',
    },
    {
      id: 81,
      country: 'Australia',
      itemName: 'Air Jordan',
      boxName: 'Nike budget',
      type: 'image',
      expansion: 'PNG',
      boxImage: 'https://skinworld-prod.s3.amazonaws.com/images/case-images/OFFCL_Nike_1.png',
      countryImage: 'assets/images/country-flags/AU.svg',
    },
  ];

  constructor(
    private titleService: Title, private toast: ToastrService
  ) {
    this.titleService.setTitle('Unboxings From Our Costomers');
  }

  showAllUnboxing() {
    if (this.unboxingsItems.length) {
      this.toast.success('No photos/videos to show');
    }
  }

  ngOnInit() {
  }
}
